# Generated by Django 3.0.2 on 2020-01-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Name must be unique', max_length=50, unique=True)),
                ('age', models.IntegerField(default=18)),
                ('contact_number', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Name must be unique', max_length=50, unique=True)),
                ('age', models.IntegerField(default=18)),
                ('contact_number', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('requested', models.BooleanField(default=False)),
                ('availability', models.BooleanField(default=True)),
                ('end_trip', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_created', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(help_text='Select the driver.', on_delete=django.db.models.deletion.CASCADE, to='systemApplication.DriverModel')),
                ('user', models.ForeignKey(help_text='Select the user.', on_delete=django.db.models.deletion.CASCADE, to='systemApplication.UserModel')),
            ],
        ),
    ]
