# Generated by Django 3.0.2 on 2020-01-21 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(help_text='Name must be unique', max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Name must be unique and Enter your name', max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RE', 'Requested'), ('AC', 'Accepted'), ('DO', 'Done')], default='DO', help_text='Select your choices for a particular user', max_length=2)),
                ('driver', models.ForeignKey(blank=True, help_text='Select the driver and it can be left null while accessing through the user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='systemApplication.DriverModel')),
                ('user', models.ForeignKey(help_text='Select the user.', on_delete=django.db.models.deletion.CASCADE, to='systemApplication.UserModel')),
            ],
        ),
    ]
