# Generated by Django 3.0.2 on 2020-01-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='end_trip',
            field=models.BooleanField(default=False),
        ),
    ]
