# Generated by Django 3.0.2 on 2020-01-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemApplication', '0002_auto_20200118_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivermodel',
            old_name='username',
            new_name='drivername',
        ),
        migrations.RemoveField(
            model_name='drivermodel',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='drivermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='drivermodel',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='drivermodel',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='end_trip',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='requested',
        ),
        migrations.AddField(
            model_name='ridedetails',
            name='status',
            field=models.CharField(choices=[('RE', 'Requested'), ('AC', 'Accepted'), ('DO', 'Done')], default='DO', help_text='Select your choices for a particular user', max_length=2),
        ),
        migrations.AlterField(
            model_name='ridedetails',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Select the driver and it can be left null while accessing through the user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='systemApplication.DriverModel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(help_text='Name must be unique and Enter your name', max_length=50, unique=True),
        ),
    ]
